import {
  AiFillHeart,
  AiFillLock,
  AiFillSignal,
  AiFillStar,
  AiOutlineAppstore,
  AiOutlineArrowLeft,
  AiOutlineArrowRight,
  AiOutlineGif,
  AiOutlineHeart,
  AiOutlineHistory,
  AiOutlineInfo,
  AiOutlineLineChart,
  AiOutlineUnorderedList,
  AiOutlineMenuFold,
  AiOutlinePicture,
  AiOutlinePercentage,
  AiOutlineQrcode,
  AiOutlineRetweet,
  AiOutlineSend,
  AiOutlineStar,
  AiOutlineSwap,
} from 'react-icons/ai'
import {
  BiDollarCircle,
  BiArrowBack,
  BiCopy,
  BiLinkExternal,
  BiMessageRounded,
  BiSelectMultiple,
  BiUndo,
} from 'react-icons/bi'
import {
  BsCurrencyDollar,
  BsDiscord,
  BsEmojiSmile,
  BsMedium,
  BsQuestion,
  BsQuestionCircle,
  BsSearch,
  BsTelegram,
  BsTwitter,
  BsTrash,
  BsExclamationCircle,
  BsYoutube,
  BsFolderSymlink,
} from 'react-icons/bs'
import { CgMenu, CgArrowsExchangeAltV, CgEye } from 'react-icons/cg'
import {
  FaChartArea,
  FaChartPie,
  FaFire,
  FaGasPump,
  FaSortDown,
  FaSortUp,
  FaWifi,
  FaArrowDown,
  FaRegCommentDots,
} from 'react-icons/fa'
import {
  FiCheck,
  FiChevronDown,
  FiChevronLeft,
  FiChevronRight,
  FiEdit,
  FiMinusCircle,
  FiPlus,
  FiPlusCircle,
  FiX,
} from 'react-icons/fi'
import { GoBook, GoSettings } from 'react-icons/go'
import {
  HiOutlineCog,
  HiOutlineChartPie,
  HiOutlineDocumentText,
} from 'react-icons/hi'
import { ImBlocked } from 'react-icons/im'
import {
  IoCheckmarkCircleOutline,
  IoCloseCircleOutline,
  IoWalletOutline,
  IoLanguage,
  IoCart,
} from 'react-icons/io5'
import {
  MdAreaChart,
  MdKeyboardArrowDown,
  MdKeyboardArrowUp,
  MdLanguage,
  MdOutlineLockOpen,
  MdSpaceBar,
  MdOutlineHdrAuto,
  MdVerified,
} from 'react-icons/md'
import { RiShareBoxLine } from 'react-icons/ri'
import {
  SlBell,
  SlBubbles,
  SlEnvolope,
  SlGameController,
  SlGlobeAlt,
  SlHandbag,
  SlHome,
  SlLock,
  SlPeople,
  SlSettings,
  SlTrophy,
  SlUser,
} from 'react-icons/sl'
import { TbCalendarTime } from 'react-icons/tb'
import {
  VscAdd,
  VscCloudUpload,
  VscError,
  VscInfo,
  VscKey,
  VscLock,
  VscSignOut,
  VscSymbolMethod,
  VscLoading,
  VscGraph,
} from 'react-icons/vsc'

const Icons = {
  account: SlUser,
  add: VscAdd,
  arrowBack: BiArrowBack,
  arrowDown: FaArrowDown,
  arrowDownLine: MdKeyboardArrowDown,
  arrowLeft: AiOutlineArrowLeft,
  arrowRight: AiOutlineArrowRight,
  arrowUp: MdKeyboardArrowUp,
  arrowUpLine: MdKeyboardArrowUp,
  auto: MdOutlineHdrAuto,
  backup: VscCloudUpload,
  barchart: AiFillSignal,
  bell: SlBell,
  blocked: ImBlocked,
  calendar: TbCalendarTime,
  cart: IoCart,
  chart: AiOutlineLineChart,
  chartArea2: FaChartArea,
  chartArea: MdAreaChart,
  chartPie: FaChartPie,
  chartPieOutline: HiOutlineChartPie,
  checkmark: FiCheck,
  chevronDown: FiChevronDown,
  chevronLeft: FiChevronLeft,
  chevronRight: FiChevronRight,
  close: FiX,
  cog: HiOutlineCog,
  copy: BiCopy,
  currencyDollar: BsCurrencyDollar,
  disconnect: VscSignOut,
  discord: BsDiscord,
  docs: GoBook,
  dollarOutlined: BiDollarCircle,
  edit: FiEdit,
  email: SlEnvolope,
  exchange: CgArrowsExchangeAltV,
  explore: SlGlobeAlt,
  external: BiLinkExternal,
  eye: CgEye,
  feedback: FaRegCommentDots,
  fire: FaFire,
  forum: SlBubbles,
  game: SlGameController,
  gas: FaGasPump,
  gif: AiOutlineGif,
  graph: VscGraph,
  grid: AiOutlineAppstore,
  heart: AiOutlineHeart,
  heartFilled: AiFillHeart,
  history: AiOutlineHistory,
  home: SlHome,
  image: AiOutlinePicture,
  import: BsFolderSymlink,
  info: AiOutlineInfo,
  infoCircle: VscInfo,
  invalid: IoCloseCircleOutline,
  key: VscKey,
  language: MdLanguage,
  languageLetters: IoLanguage,
  league: SlTrophy,
  list: AiOutlineUnorderedList,
  loader: VscLoading,
  lock: VscLock,
  lockFill: AiFillLock,
  medium: BsMedium,
  menu: CgMenu,
  menuFold: AiOutlineMenuFold,
  minusCircle: FiMinusCircle,
  multiSettings: GoSettings,
  node: VscSymbolMethod,
  password: SlLock,
  people: SlPeople,
  percent: AiOutlinePercentage,
  plus: FiPlus,
  plusCircle: FiPlusCircle,
  qrcode: AiOutlineQrcode,
  question: BsQuestion,
  questionCircle: BsQuestionCircle,
  reply: BiMessageRounded,
  retweet: AiOutlineRetweet,
  revert: BiUndo,
  search: BsSearch,
  selectAll: BiSelectMultiple,
  send: AiOutlineSend,
  settings: SlSettings,
  share: RiShareBoxLine,
  smile: BsEmojiSmile,
  sortDown: FaSortDown,
  sortUp: FaSortUp,
  spaceBar: MdSpaceBar,
  starEmpty: AiOutlineStar,
  starFilled: AiFillStar,
  store: SlHandbag,
  switch: AiOutlineSwap,
  telegram: BsTelegram,
  trash: BsTrash,
  twitter: BsTwitter,
  unlock: MdOutlineLockOpen,
  valid: IoCheckmarkCircleOutline,
  verified: MdVerified,
  wallet: IoWalletOutline,
  warn: BsExclamationCircle,
  wifi: FaWifi,
  xCircle: VscError,
  youtube: BsYoutube,
  documentation: HiOutlineDocumentText,
} as const

export default Icons
